version: "3"

services:

  nginx:
    image: codecov/nginx
    ports:
      - "8888"
    environment:
      - MINIO_ACCESS_KEY=default-key
      - MINIO_SECRET_KEY=default-secret
      - S3_BUCKET_NAME=archive
    networks:
      - codecov

  minio:
    image: minio/minio:RELEASE.2018-10-06T00-15-16Z
    command: server /export
    ports:
      - "9000"
    environment:
      - MINIO_ACCESS_KEY=default-key
      - MINIO_SECRET_KEY=default-secret
    volumes:
      - archive-volume:/export
    networks:
      - codecov

volumes:
  archive-volume:

networks:
  codecov:
    driver: bridge
